name: Docker Bench Security

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  docker-bench-security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Docker
        run: |
          sudo apt update
          sudo apt install -y docker.io

      - name: Clone Docker Bench Security
        run: |
          git clone https://github.com/docker/docker-bench-security.git
          cd docker-bench-security
          sudo chmod +x docker-bench-security.sh

      - name: Run Docker Bench Security
        run: |
          cd docker-bench-security
          sudo ./docker-bench-security.sh
